name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: fmt
        run: cargo fmt --check

      - name: clippy
        run: cargo clippy -- -D warnings

      - name: test
        run: cargo test
